<?php namespace App\Connectors\Sap\Di\Server\Handlers;

use App\Exceptions\BadRequestException;

class Response extends \DOMDocument
{
    private $xpath;

    public function loadXML($source, $options = null)
    {
        parent::loadXML($source, $options); // TODO: Change the autogenerated stub

        $this->xpath = new \DOMXPath($this);
        $this->xpath->registerNamespace('env', 'http://www.w3.org/2003/05/soap-envelope');
        $this->xpath->registerNamespace('xmlns', 'http://www.sap.com/SBO/DIS');

        $this->checkFaults();
    }

    public function getValueByQuery($string) {
        try {
            $node = $this->xpath->evaluate('//env:Body/'.$string)->item(0)->nodeValue;
        } catch (\Exception $e) {
            throw $e;
        }

        return $node;
    }

    public function checkFaults()
    {
        $faultPath = '//env:Body/env:Fault';

        if ($this->xpath->query('//env:Body/env:Fault')) {
            throw new BadRequestException([
                [
                    'error' => $this->xpath->query($faultPath.'/env:Reason/env:Text')->item(0)->nodeValue,
                    'value' => $this->xpath->query($faultPath.'/env:Detail/ErrorList/Error')->item(0)->nodeValue
                ]
            ]);
        }
    }
}